### ISSUE TITLE
Don't allow `global` anymore, use static variables at package level instead

### ISSUE THREAD

**Issue by StunxFS** [tiabeast/bait#249]
### Describe the feature

From the documentation:

![image](https://github.com/user-attachments/assets/a5c39df6-2dd6-4b3b-ba46-e21ad4aa7626)

If the use of `global` is discouraged, then it is preferable to remove it completely from the language and use static variables at the package level.

### Proposed Solution

Static variables at the package level are safer to use, plus they are declared in a package scope, so there is no collision with other symbols with similar names.

```go
package main

static my_var := 1

fun main() {
    my_var += 1
}
```

**Comment by serkonda7** [comment]
To reduce issues with globals, they already behave like static variables.
The keyword should indeed be changed to `static` plus update of the docs and syntax design document.
